production: false
dispatchers:
  service:
    consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    consumer_key: xxxxxxxxxxxxxxxxxxxxxxxxxx
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    token_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
openweathermap:
  city_id: 5913490
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  units: metric
