production: false
dispatchers:
  mastodon:
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  bluesky:
    identifier: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
openweathermap:
  city_id: 5913490
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  units: metric
