---
name: Ruby
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
permissions:
  contents: read
jobs:
  rake:
    uses: dafyddcrosby/dc-github-actions/.github/workflows/bundle_rake.yml@main
